### ISSUE TITLE
Computational resources

### ISSUE THREAD

**Issue by azzaea** [Omer80/NetStruct_python#2]
Hello,

I'm editing because that was an old error. I'm running agian, and it seems to work. However, I see no indication of where the results are.

All I can find in the log is this message:
```
Please specify full file name
Constructing genetic similarity matrix
```

And below is the error trace:
```
+ python netstruct.py -b out.netstructformat.csv
Traceback (most recent call last):
  File "netstruct.py", line 497, in <module>
    main(args)
  File "netstruct.py", line 393, in main
    buildGDmatrix(args.createGDmatrix,args.outfname)
  File "netstruct.py", line 44, in __init__
    self.data = data
UnboundLocalError: local variable 'data' referenced before assignment
```

Would you kindly advise?
Thanks,
Azza

**Comment by azzaea** [comment]
It seems I'm mis-specifying inputs to the tool, hence the errors.

I'm wondering if you made performance comparisons with the Mathematica version? For my small dataset (1239 individuals * 2849 snps), it took 3.5 hours just to generate the Genetic Distance matrix.
Is this normal?

Thanks,
Azza

**Comment by omertzuk** [comment]
I haven't done such comparison between Python and Mathematica.

You can probable accelerate some of the parts of the code using Numba or Cython.

Best,
Omer

**Comment by azzaea** [comment]
Thanks. 

I guess this settles it. I will close the issue and get back to you if I faced other problems.
